/**
 * Обработчик генерации уникального фото через OpenRouter
 * Использует gemini-3-pro-image-preview для генерации
 */

import { OrderService } from './order.js';

export async function processUniquePhoto(env, message) {
  const { orderId, telegramId, chatId, prompt, photoUrl } = message;
  
  try {
    console.log(`Processing unique photo for order ${orderId}`);

    // Проверяем что все необходимые переменные есть
    if (!env.OPENROUTER_API_KEY) {
      throw new Error('OPENROUTER_API_KEY is not configured. Please set it using: wrangler secret put OPENROUTER_API_KEY');
    }

    if (!env.BOT_TOKEN) {
      throw new Error('BOT_TOKEN is not configured');
    }

    const orderService = new OrderService(env.DB);
    
    // 1. Обновляем статус на processing
    await orderService.markOrderAsProcessing(orderId);

    // 2. Отправляем уведомление
    await sendTelegramNotification(
      env.BOT_TOKEN,
      chatId,
      '⏳ Генерируем ваше уникальное фото...'
    );

    // 2.5. Получаем исходное фото из R2 и конвертируем в base64
    console.log(`Loading photo from R2: ${photoUrl}`);
    const r2Object = await env.BUCKET.get(photoUrl);
    if (!r2Object) {
      throw new Error(`Photo not found in R2: ${photoUrl}`);
    }
    
    const photoArrayBuffer = await r2Object.arrayBuffer();
    const photoBytes = new Uint8Array(photoArrayBuffer);
    
    // Конвертируем в base64 через Web API
    let base64Photo = '';
    const binaryString = Array.from(photoBytes)
      .map(byte => String.fromCharCode(byte))
      .join('');
    base64Photo = btoa(binaryString);
    
    const photoDataUrl = `data:image/jpeg;base64,${base64Photo}`;
    console.log(`Photo converted to base64, length: ${base64Photo.length}`);

    // 3. Вызываем OpenRouter API с фото + промптом
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${env.OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-3-pro-image-preview',
        messages: [
          {
            role: 'user',
            content: [
              {
                type: 'text',
                text: prompt
              },
              {
                type: 'image_url',
                image_url: {
                  url: photoDataUrl
                }
              }
            ]
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      const errorStatus = response.status;
      console.error(`OpenRouter API error (${errorStatus}):`, errorText);
      throw new Error(`OpenRouter API error (${errorStatus}): ${errorText}`);
    }

    const result = await response.json();
    console.log('OpenRouter response:', JSON.stringify(result, null, 2));

    // 4. Проверяем что ответ имеет правильную структуру
    if (!result.choices || !Array.isArray(result.choices) || result.choices.length === 0) {
      console.error('Invalid response structure from OpenRouter:', result);
      throw new Error('Invalid response structure from OpenRouter - no choices');
    }

    const choice = result.choices[0];
    if (!choice.message) {
      console.error('Invalid message in choice:', choice);
      throw new Error('Invalid response structure - no message in choice');
    }

    // Детальное логирование структуры ответа
    console.log('Message structure:', JSON.stringify({
      hasContent: !!choice.message.content,
      hasImages: !!choice.message.images,
      contentType: typeof choice.message.content,
      imagesType: typeof choice.message.images,
      messageKeys: Object.keys(choice.message)
    }));

    // Проверяем есть ли изображения в ответе
    if (!choice.message.images) {
      console.error('No images in response. Full message:', JSON.stringify(choice.message, null, 2));
      throw new Error('No images generated by OpenRouter - check model compatibility and credits');
    }

    const images = choice.message.images;
    if (!Array.isArray(images) || images.length === 0) {
      console.error('Images is not array or empty:', images);
      throw new Error('Images array is empty or invalid');
    }

    console.log(`Received ${images.length} images from OpenRouter`);
    const resultUrls = [];

    // 5. Сохраняем каждое изображение в R2
    for (let i = 0; i < images.length; i++) {
      const image = images[i];
      
      console.log(`Processing image ${i + 1}:`, JSON.stringify(image).substring(0, 200));

      // Проверяем структуру изображения
      if (!image.image_url || !image.image_url.url) {
        console.error(`Invalid image structure at index ${i}:`, image);
        throw new Error(`Invalid image structure at index ${i}`);
      }

      const imageUrl = image.image_url.url;
      
      let imageBuffer;

      // Проверяем если это base64 data URL или обычный URL
      if (imageUrl.startsWith('data:')) {
        // Base64 data URL - декодируем через Web API (без Node.js Buffer)
        const base64Data = imageUrl.split(',')[1];
        if (!base64Data) {
          throw new Error(`Invalid base64 data URL at index ${i}`);
        }
        
        // Декодируем base64 в бинарные данные (Web API)
        const binaryString = atob(base64Data);
        const bytes = new Uint8Array(binaryString.length);
        for (let j = 0; j < binaryString.length; j++) {
          bytes[j] = binaryString.charCodeAt(j);
        }
        imageBuffer = bytes.buffer;
        
      } else if (imageUrl.startsWith('http')) {
        // Скачиваем с URL
        console.log(`Downloading image from URL: ${imageUrl.substring(0, 100)}...`);
        const imgResponse = await fetch(imageUrl);
        if (!imgResponse.ok) {
          throw new Error(`Failed to download image from URL: ${imgResponse.status}`);
        }
        imageBuffer = await imgResponse.arrayBuffer();
      } else {
        throw new Error(`Unknown image URL format at index ${i}: ${imageUrl.substring(0, 100)}`);
      }

      // Сохраняем в R2
      const r2Key = `output/${orderId}/result_${i + 1}_${Date.now()}.jpg`;
      await env.BUCKET.put(r2Key, imageBuffer, {
        httpMetadata: {
          contentType: 'image/jpeg'
        }
      });

      resultUrls.push(`r2://${r2Key}`);
      console.log(`Saved image ${i + 1} to R2: ${r2Key}`);
    }

    // 6. Обновляем заказ на completed с результатами
    if (resultUrls.length === 0) {
      throw new Error('No result URLs were generated');
    }

    const resultData = { urls: resultUrls, generated_at: new Date().toISOString() };
    console.log(`Updating order ${orderId} with results:`, JSON.stringify(resultData));
    
    await orderService.markOrderAsCompleted(orderId, JSON.stringify(resultData));

    // 7. Отправляем результат пользователю
    // Генерируем публичные ссылки (если нужно) или отправляем через Telegram
    for (let i = 0; i < resultUrls.length; i++) {
      const r2Path = resultUrls[i].replace('r2://', '');
      
      // Получаем файл из R2
      const r2Object = await env.BUCKET.get(r2Path);
      if (!r2Object) {
        console.error(`Failed to get ${r2Path} from R2`);
        continue;
      }

      const arrayBuffer = await r2Object.arrayBuffer();
      
      // Отправляем фото в Telegram
      await sendPhotoToTelegram(
        env.BOT_TOKEN,
        chatId,
        arrayBuffer,
        i === 0 ? `✅ Ваше уникальное фото готово!\n\n📝 Промпт: ${prompt}` : null
      );
    }

    console.log(`Order ${orderId} completed successfully`);

  } catch (error) {
    console.error('Error processing unique photo:', error);
    
    // Уведомляем пользователя об ошибке
    try {
      await sendTelegramNotification(
        env.BOT_TOKEN,
        chatId,
        `❌ Произошла ошибка при генерации фото.\n\nПопробуйте еще раз или обратитесь в поддержку.\n\nОшибка: ${error.message}`
      );
    } catch (e) {
      console.error('Could not send error notification:', e);
    }
  }
}

/**
 * Отправляет текстовое уведомление в Telegram
 */
async function sendTelegramNotification(botToken, chatId, text) {
  const url = `https://api.telegram.org/bot${botToken}/sendMessage`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: text,
        parse_mode: 'HTML'
      })
    });

    if (!response.ok) {
      const error = await response.json();
      console.error('Telegram error:', error);
    }
  } catch (error) {
    console.error('Error sending Telegram notification:', error);
  }
}

/**
 * Отправляет фото в Telegram
 */
async function sendPhotoToTelegram(botToken, chatId, photoBuffer, caption = null) {
  const url = `https://api.telegram.org/bot${botToken}/sendPhoto`;

  try {
    // Создаем FormData для отправки файла
    const formData = new FormData();
    formData.append('chat_id', chatId);
    formData.append('photo', new Blob([photoBuffer], { type: 'image/jpeg' }), 'photo.jpg');
    
    if (caption) {
      formData.append('caption', caption);
    }

    const response = await fetch(url, {
      method: 'POST',
      body: formData
    });

    if (!response.ok) {
      const error = await response.json();
      console.error('Telegram photo send error:', error);
    }
  } catch (error) {
    console.error('Error sending photo to Telegram:', error);
  }
}
